# Generated by Django 3.0.8 on 2020-07-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пред показ'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
