# Generated by Django 3.0.8 on 2020-07-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200731_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_description',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Пред показ'),
        ),
    ]
