# Generated by Django 3.0.8 on 2020-08-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
